// utils/i18n.js
// All UI strings in Arabic (ar) and English (en)
// To switch language, change DEFAULT_LANG below.

export const DEFAULT_LANG = 'ar'; // 'ar' or 'en'

const strings = {
  ar: {
    // App
    appName: 'ماسح المخزون',
    loading: 'جارٍ التحميل...',
    dbError: 'خطأ في قاعدة البيانات',

    // Tabs
    tabScanner:  'الماسح',
    tabProducts: 'المنتجات',
    tabHistory:  'السجل',
    tabExport:   'تصدير',

    // Scanner
    saleMode:      'وضع البيع',
    purchaseMode:  'وضع الشراء',
    switchMode:    'تبديل',
    scannedItems:  'العناصر الممسوحة',
    clearAll:      'مسح الكل',
    confirmSale:   'تأكيد البيع',
    confirmPurchase: 'تأكيد الشراء',
    scanPrompt:    'وجّه الكاميرا نحو الباركود',
    unknownBarcode: 'باركود غير معروف',
    unknownMsg:    'هذا المنتج غير مسجل.',
    ignore:        'تجاهل',
    register:      'تسجيل',
    confirmTitle:  'تأكيد',
    confirmMsg:    (qty, count) => `${qty} وحدة في ${count} منتج. المتابعة؟`,
    savedSuccess:  'تم الحفظ بنجاح',
    emptyQueue:    'لا توجد عناصر',
    clearAllTitle: 'مسح الكل',
    clearAllMsg:   'إزالة جميع العناصر الممسوحة؟',
    lowStock:      (n) => `${n} منخفض المخزون`,
    cameraRequest: 'جارٍ طلب إذن الكاميرا...',
    cameraDenied:  'تم رفض إذن الكاميرا',
    cameraHint:    'الإعدادات ← التطبيقات ← ماسح المخزون ← الأذونات',
    items:         (n) => `(${n} وحدة)`,

    // Products
    productTitle:    'المنتجات',
    searchProducts:  'ابحث بالاسم أو الباركود...',
    addProduct:      'إضافة منتج',
    editProduct:     'تعديل منتج',
    saveProduct:     'حفظ المنتج',
    updateProduct:   'تحديث المنتج',
    deleteProduct:   'حذف المنتج',
    deleteProductMsg: (name) => `حذف "${name}"؟ لن يؤثر على سجل المعاملات.`,
    barcode:         'الباركود *',
    productName:     'اسم المنتج *',
    currentStock:    'المخزون الحالي',
    minStock:        'الحد الأدنى للتنبيه',
    unit:            'الوحدة',
    price:           'السعر (اختياري)',
    noProducts:      'لا توجد منتجات',
    addFirst:        '+ أضف أول منتج',
    lowOnly:         'منخفض المخزون فقط',
    showAll:         'عرض الكل',
    noLowStock:      'لا توجد منتجات منخفضة المخزون 🎉',
    minLabel:        (n) => `حد: ${n}`,
    barcodeRequired: 'الباركود مطلوب',
    nameRequired:    'اسم المنتج مطلوب',
    cancel:          'إلغاء',
    delete:          'حذف',

    // History
    historyTitle:   'سجل المعاملات',
    transactions:   'المعاملات',
    sold:           'مُباع',
    purchased:      'مُشترى',
    searchHistory:  'ابحث بالاسم أو الباركود...',
    all:            'الكل',
    sale:           'بيع',
    purchase:       'شراء',
    noHistory:      'لا توجد معاملات',
    clearHistory:   'مسح كل السجل',
    clearHistoryMsg: 'حذف كل سجل المعاملات؟ لا يمكن التراجع.',
    deleteAll:      'حذف الكل',
    exportCSV:      'تصدير CSV',

    // Export
    exportTitle:    'تصدير البيانات',
    productsExport: 'مخزون المنتجات',
    productsDesc:   (n) => `تصدير ${n} منتج مع مستويات المخزون والأسعار.`,
    historyExport:  'سجل المعاملات',
    historyDesc:    (n) => `تصدير ${n} معاملة (مبيعات ومشتريات).`,
    fullExport:     'تصدير كامل',
    fullDesc:       'تصدير المنتجات والسجل في ملف واحد.',
    exportBtn:      (label) => `تصدير ${label}`,
    exportNote:     'يمكن فتح ملفات CSV في Excel أو Google Sheets. يمكن مشاركتها عبر واتساب أو البريد الإلكتروني.',
    emptyExport:    'لا توجد بيانات للتصدير',
    exportFailed:   'فشل التصدير',
    exportDone:     'تم التصدير',
    noSharing:      'المشاركة غير متاحة على هذا الجهاز',
    productsLabel:  'منتج',
    historyLabel:   'معاملة',
    lowStockLabel:  'مخزون منخفض',
  },

  en: {
    appName: 'Inventory Scanner',
    loading: 'Loading...',
    dbError: 'Database error',

    tabScanner:  'Scanner',
    tabProducts: 'Products',
    tabHistory:  'History',
    tabExport:   'Export',

    saleMode:      'SALE MODE',
    purchaseMode:  'PURCHASE MODE',
    switchMode:    'Switch',
    scannedItems:  'Scanned Items',
    clearAll:      'Clear All',
    confirmSale:   'Confirm Sale',
    confirmPurchase: 'Confirm Purchase',
    scanPrompt:    'Point the camera at a barcode',
    unknownBarcode: 'Unknown Barcode',
    unknownMsg:    'This product is not registered.',
    ignore:        'Ignore',
    register:      'Register',
    confirmTitle:  'Confirm',
    confirmMsg:    (qty, count) => `${qty} item(s) across ${count} product(s). Proceed?`,
    savedSuccess:  'Transaction saved successfully',
    emptyQueue:    'No items scanned',
    clearAllTitle: 'Clear All',
    clearAllMsg:   'Remove all scanned items?',
    lowStock:      (n) => `${n} Low Stock`,
    cameraRequest: 'Requesting camera access…',
    cameraDenied:  'Camera permission denied',
    cameraHint:    'Settings → Apps → Inventory Scanner → Permissions',
    items:         (n) => `(${n} items)`,

    productTitle:    'Products',
    searchProducts:  'Search by name or barcode…',
    addProduct:      'Add Product',
    editProduct:     'Edit Product',
    saveProduct:     'Save Product',
    updateProduct:   'Update Product',
    deleteProduct:   'Delete Product',
    deleteProductMsg: (name) => `Delete "${name}"? History will not be deleted.`,
    barcode:         'Barcode *',
    productName:     'Product Name *',
    currentStock:    'Current Stock',
    minStock:        'Min Stock Alert',
    unit:            'Unit',
    price:           'Price (optional)',
    noProducts:      'No products found',
    addFirst:        '+ Add First Product',
    lowOnly:         'Low Stock Only',
    showAll:         'Show All',
    noLowStock:      'No low-stock products 🎉',
    minLabel:        (n) => `min ${n}`,
    barcodeRequired: 'Barcode is required',
    nameRequired:    'Product name is required',
    cancel:          'Cancel',
    delete:          'Delete',

    historyTitle:   'Transaction History',
    transactions:   'Transactions',
    sold:           'Sold',
    purchased:      'Purchased',
    searchHistory:  'Search by name or barcode…',
    all:            'ALL',
    sale:           'SALE',
    purchase:       'PURCHASE',
    noHistory:      'No transactions found',
    clearHistory:   'Clear All History',
    clearHistoryMsg: 'Delete all transaction history? This cannot be undone.',
    deleteAll:      'Delete All',
    exportCSV:      'CSV',

    exportTitle:    'Export Data',
    productsExport: 'Products Inventory',
    productsDesc:   (n) => `Export all ${n} products with stock levels and prices.`,
    historyExport:  'Transaction History',
    historyDesc:    (n) => `Export all ${n} transactions (sales & purchases).`,
    fullExport:     'Full Export',
    fullDesc:       'Export both products and history in one combined CSV.',
    exportBtn:      (label) => `Export ${label}`,
    exportNote:     'CSV files can be opened in Excel or Google Sheets. Share via WhatsApp, email, etc.',
    emptyExport:    'No data to export',
    exportFailed:   'Export failed',
    exportDone:     'Exported',
    noSharing:      'Sharing not available on this device',
    productsLabel:  'Products',
    historyLabel:   'Transactions',
    lowStockLabel:  'Low Stock',
  }
};

// Active language
let _lang = DEFAULT_LANG;
export const setLanguage = (lang) => { _lang = lang; };
export const getLanguage = () => _lang;
export const t = (key, ...args) => {
  const val = strings[_lang]?.[key] ?? strings['en']?.[key] ?? key;
  return typeof val === 'function' ? val(...args) : val;
};
export const isRTL = () => _lang === 'ar';
